import type {GuidedTourRegistry} from '@/components/guided-tour/ports/types.ts';

export const RAC_EDITOR_TOUR_ID = 'rac-editor-intro';

const RAC_CANVAS_OBJECT_INSERTED_EVENT = 'rac:canvas-object-inserted';
const RAC_HOUSE_TOP_VIEW_INSERTED_EVENT = 'rac:house-top-view-inserted';
const RAC_HOUSE_ELEVATION_VIEW_INSERTED_EVENT = 'rac:house-elevation-view-inserted';
const RAC_CONSTRUCTION_ADD_TOUR_READY_EVENT = 'rac:construction-add-tour-ready';
const RAC_CONSTRUCTION_ACTIONS_TOUR_READY_EVENT = 'rac:construction-actions-tour-ready';
const RAC_CONSTRUCTION_BACK_TO_CANVAS_TOUR_READY_EVENT = 'rac:construction-back-to-canvas-tour-ready';
const RAC_HOUSE_ADD_TOUR_READY_EVENT = 'rac:house-add-tour-ready';
const RAC_HOUSE_ACTIONS_TOUR_READY_EVENT = 'rac:house-actions-tour-ready';
const RAC_HOUSE_TOP_VIEW_STORAGE_REVISION = 'piloti-target';
const RAC_CONSTRUCTION_ADD_STORAGE_REVISION = 'construction-add-v1';
const RAC_CONSTRUCTION_ACTIONS_STORAGE_REVISION = 'construction-actions-v2';
const RAC_CONSTRUCTION_BACK_TO_CANVAS_STORAGE_REVISION = 'construction-back-to-canvas-v1';
const RAC_HOUSE_ADD_STORAGE_REVISION = 'house-add-v1';
const RAC_HOUSE_ACTIONS_STORAGE_REVISION = 'house-actions-v1';

export const racEditorGuidedTourRegistry: GuidedTourRegistry = {
  tours: [
    {
      id: RAC_EDITOR_TOUR_ID,
      initialStepId: 'rac-hamburger',
      persistKey: 'guided-tour:rac-editor-intro:completed',
      autoStart: true,
      steps: [
        {
          id: 'rac-hamburger',
          targetId: 'rac-hamburger',
          placement: 'right',
          alignment: 'middle',
          title: 'Menu Principal',
          text: 'Use o menu principal para alternar entre as casas da Construção TETO ativa.',
          next: 'rac-user-menu',
          persistKey: 'guided-tour:rac-editor-intro:hamburger',
          kind: 'flow',
        },
        {
          id: 'rac-user-menu',
          targetId: 'rac-user-menu',
          placement: 'bottom',
          alignment: 'right',
          title: 'Perfil e Ajuda',
          text: 'Aqui ficam configurações, dicas e o acesso manual a este tutorial.',
          next: 'rac-export-pdf',
          persistKey: 'guided-tour:rac-editor-intro:user-menu',
          kind: 'flow',
        },
        {
          id: 'rac-export-pdf',
          targetId: 'rac-export-pdf',
          placement: 'bottom',
          alignment: 'right',
          title: 'Exportar PDF',
          text: 'Exporte o RAC em PDF quando precisar compartilhar a planta final.',
          next: 'rac-view-3d',
          persistKey: 'guided-tour:rac-editor-intro:export-pdf',
          kind: 'flow',
        },
        {
          id: 'rac-view-3d',
          targetId: 'rac-view-3d',
          placement: 'bottom',
          alignment: 'center',
          title: 'Visualização 3D',
          text: 'Abra a visualização 3D para conferir a casa em volume.',
          next: 'rac-zoom-menu',
          persistKey: 'guided-tour:rac-editor-intro:view-3d',
          kind: 'flow',
        },
        {
          id: 'rac-zoom-menu',
          targetId: 'rac-zoom-menu',
          placement: 'bottom',
          alignment: 'center',
          title: 'Zoom',
          text: 'O zoom também reúne seleção, navegação e ajuste da tela.',
          next: 'rac-house-difficulty-controls',
          persistKey: 'guided-tour:rac-editor-intro:zoom',
          kind: 'flow',
        },
        {
          id: 'rac-house-difficulty-controls',
          targetId: 'rac-house-difficulty-controls',
          placement: 'left',
          alignment: 'middle',
          title: 'Dificuldade da Casa',
          text: 'Este medidor resume a dificuldade estimada da construção. Use os ícones para ajustar solo, hidráulicos, subterrâneos, elevados e esquadro.',
          next: 'rac-toolbar',
          persistKey: 'guided-tour:rac-editor-intro:difficulty-controls',
          kind: 'flow',
        },
        {
          id: 'rac-toolbar',
          targetId: 'rac-toolbar',
          placement: 'right',
          alignment: 'middle',
          title: 'Barra de Ferramentas',
          text: 'A barra lateral concentra casas, elementos, linhas e ações de desenho.',
          persistKey: 'guided-tour:rac-editor-intro:toolbar',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-house-top-view',
      initialStepId: 'rac-house-top-view',
      persistKey: 'guided-tour:rac-house-top-view:completed',
      storageRevision: RAC_HOUSE_TOP_VIEW_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_HOUSE_TOP_VIEW_INSERTED_EVENT,
        objectKind: 'house-top-view-inserted',
      },
      steps: [
        {
          id: 'rac-house-top-view',
          targetId: 'house-top-view',
          placement: 'bottom',
          alignment: 'center',
          title: 'Vista Planta',
          text: 'A vista planta mostra a casa por cima e organiza os pilotis usados como referência no desenho. Ao clicar em um dos pilotis é possível editar altura, nível e/ou contraventamento.',
          next: 'rac-house-piloti',
          persistKey: 'guided-tour:rac-house-top-view:top-view',
          kind: 'flow',
        },
        {
          id: 'rac-house-piloti',
          targetId: 'house-top-view-piloti',
          placement: 'top',
          alignment: 'center',
          text: 'Na planta superior, selecione um piloti para abrir o editor e ajustar altura, nível e contraventamento quando necessário.',
          persistKey: 'guided-tour:rac-house-top-view:piloti',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-house-elevation-view',
      initialStepId: 'rac-house-elevation-view',
      persistKey: 'guided-tour:rac-house-elevation-view:completed',
      triggerEvent: {
        name: RAC_HOUSE_ELEVATION_VIEW_INSERTED_EVENT,
        objectKind: 'house-elevation-view-inserted',
      },
      steps: [
        {
          id: 'rac-house-elevation-view',
          targetId: 'house-elevation-view',
          placement: 'top',
          alignment: 'center',
          title: 'Vista Elevada',
          text: 'A vista elevada mostra a fachada posicionada sobre o terreno e reflete os níveis definidos nos pilotis. Ao clicar duas vezes sobre o terreno é possível editar o nível de dificuldade para cálculo de pedras.',
          persistKey: 'guided-tour:rac-house-elevation-view:elevation-view',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-construction-add',
      initialStepId: 'rac-construction-add',
      persistKey: 'guided-tour:rac-construction-add:completed',
      storageRevision: RAC_CONSTRUCTION_ADD_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_CONSTRUCTION_ADD_TOUR_READY_EVENT,
        objectKind: 'construction-add',
      },
      steps: [
        {
          id: 'rac-construction-add',
          targetId: 'rac-construction-add',
          placement: 'bottom',
          alignment: 'right',
          title: 'Adicionar Construção',
          text: 'Crie uma nova Construção TETO para registrar comunidade, data, famílias, casas e monitores em um único fluxo.',
          persistKey: 'guided-tour:rac-construction-add:add',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-construction-actions',
      initialStepId: 'rac-construction-monitors',
      persistKey: 'guided-tour:rac-construction-actions:completed',
      storageRevision: RAC_CONSTRUCTION_ACTIONS_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_CONSTRUCTION_ACTIONS_TOUR_READY_EVENT,
        objectKind: 'construction-actions',
      },
      steps: [
        {
          id: 'rac-construction-monitors',
          targetId: 'rac-construction-monitors',
          placement: 'bottom',
          alignment: 'center',
          title: 'Monitores',
          text: 'Use este atalho para cadastrar e editar a equipe responsável pela construção selecionada.',
          next: 'rac-construction-houses',
          persistKey: 'guided-tour:rac-construction-actions:monitors',
          kind: 'flow',
        },
        {
          id: 'rac-construction-houses',
          targetId: 'rac-construction-houses',
          placement: 'bottom',
          alignment: 'center',
          title: 'Casas e Famílias',
          text: 'Aqui você acessa as casas da construção, configura famílias, dificuldade, materiais e o desenho RAC de cada casa.',
          next: 'rac-construction-export-racs',
          persistKey: 'guided-tour:rac-construction-actions:houses',
          kind: 'flow',
        },
        {
          id: 'rac-construction-export-racs',
          targetId: 'rac-construction-export-racs',
          placement: 'bottom',
          alignment: 'center',
          title: 'Exportar RACs',
          text: 'Gere um ZIP com as RACs das casas não arquivadas desta construção quando ela estiver em andamento.',
          next: 'rac-construction-completed',
          persistKey: 'guided-tour:rac-construction-actions:export-racs',
          kind: 'flow',
        },
        {
          id: 'rac-construction-completed',
          targetId: 'rac-construction-completed',
          placement: 'bottom',
          alignment: 'center',
          title: 'Construção Concluída',
          text: 'Use este botão para marcar a construção como concluída. Quando isso acontece, casas e monitores ficam somente para visualização até voltar para andamento.',
          next: 'rac-construction-archive',
          persistKey: 'guided-tour:rac-construction-actions:completion',
          kind: 'flow',
        },
        {
          id: 'rac-construction-archive',
          targetId: 'rac-construction-archive',
          placement: 'bottom',
          alignment: 'center',
          title: 'Arquivar Construção',
          text: 'Arquive ou desarquive uma construção sem abrir a edição. A confirmação evita mudanças acidentais.',
          persistKey: 'guided-tour:rac-construction-actions:archive',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-construction-back-to-canvas',
      initialStepId: 'rac-construction-back-to-canvas',
      persistKey: 'guided-tour:rac-construction-back-to-canvas:completed',
      storageRevision: RAC_CONSTRUCTION_BACK_TO_CANVAS_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_CONSTRUCTION_BACK_TO_CANVAS_TOUR_READY_EVENT,
        objectKind: 'construction-back-to-canvas',
      },
      steps: [
        {
          id: 'rac-construction-back-to-canvas',
          targetId: 'rac-construction-back-to-canvas',
          placement: 'right',
          alignment: 'middle',
          title: 'Voltar ao Canvas',
          text: 'Use este botão para retornar ao canvas da casa ativa depois de criar, arquivar, listar ou trocar construções.',
          persistKey: 'guided-tour:rac-construction-back-to-canvas:back',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-house-add',
      initialStepId: 'rac-house-add',
      persistKey: 'guided-tour:rac-house-add:completed',
      storageRevision: RAC_HOUSE_ADD_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_HOUSE_ADD_TOUR_READY_EVENT,
        objectKind: 'house-add',
      },
      steps: [
        {
          id: 'rac-house-add',
          targetId: 'rac-house-add',
          placement: 'bottom',
          alignment: 'right',
          title: 'Adicionar Casa',
          text: 'Crie uma nova casa para configurar família, terreno, pilotis e desenho RAC dentro da construção selecionada.',
          persistKey: 'guided-tour:rac-house-add:add',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-house-actions',
      initialStepId: 'rac-house-status',
      persistKey: 'guided-tour:rac-house-actions:completed',
      storageRevision: RAC_HOUSE_ACTIONS_STORAGE_REVISION,
      triggerEvent: {
        name: RAC_HOUSE_ACTIONS_TOUR_READY_EVENT,
        objectKind: 'house-actions',
      },
      steps: [
        {
          id: 'rac-house-status',
          targetId: 'rac-house-status',
          placement: 'bottom',
          alignment: 'center',
          title: 'Status da Casa',
          text: 'O status mostra a etapa atual da casa, como rascunho, RAC impresso, construída ou arquivada.',
          next: 'rac-house-difficulty',
          persistKey: 'guided-tour:rac-house-actions:status',
          kind: 'flow',
        },
        {
          id: 'rac-house-difficulty',
          targetId: 'rac-house-difficulty',
          placement: 'bottom',
          alignment: 'center',
          title: 'Dificuldade',
          text: 'Este medidor resume a dificuldade estimada a partir dos níveis dos pilotis, solo e obstáculos informados.',
          next: 'rac-house-extra-materials',
          persistKey: 'guided-tour:rac-house-actions:difficulty',
          kind: 'flow',
        },
        {
          id: 'rac-house-extra-materials',
          targetId: 'rac-house-extra-materials',
          placement: 'bottom',
          alignment: 'center',
          title: 'Materiais Extras',
          text: 'Use este atalho para registrar materiais extras e justificativas específicas da casa.',
          next: 'rac-house-built',
          persistKey: 'guided-tour:rac-house-actions:extra-materials',
          kind: 'flow',
        },
        {
          id: 'rac-house-built',
          targetId: 'rac-house-built',
          placement: 'bottom',
          alignment: 'center',
          title: 'Casa Construída',
          text: 'Use este botão para marcar a casa como construída. Quando isso acontece, a edição da casa e do canvas fica bloqueada até voltar para rascunho.',
          next: 'rac-house-archive',
          persistKey: 'guided-tour:rac-house-actions:built',
          kind: 'flow',
        },
        {
          id: 'rac-house-archive',
          targetId: 'rac-house-archive',
          placement: 'bottom',
          alignment: 'center',
          title: 'Arquivar Casa',
          text: 'Arquive ou desarquive uma casa sem abrir a edição. A confirmação evita mudanças acidentais.',
          next: 'rac-house-back',
          persistKey: 'guided-tour:rac-house-actions:archive',
          kind: 'flow',
        },
        {
          id: 'rac-house-back',
          targetId: 'rac-house-back',
          placement: 'right',
          alignment: 'middle',
          title: 'Voltar para Construções',
          text: 'Use esta seta para voltar à listagem da construção selecionada.',
          persistKey: 'guided-tour:rac-house-actions:back',
          kind: 'flow',
        },
      ],
    },
  ],
  tips: [
    {
      id: 'rac-tip-wall',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'wall'},
      placement: 'left',
      alignment: 'middle',
      text: 'Depois de inserir um objeto ou muro, dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:wall',
      kind: 'tip',
    },
    {
      id: 'rac-tip-line',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'line'},
      placement: 'left',
      alignment: 'middle',
      text: 'Linhas podem receber texto e cor pelo editor do próprio objeto. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:line',
      kind: 'tip',
    },
    {
      id: 'rac-tip-arrow',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'arrow'},
      placement: 'left',
      alignment: 'middle',
      text: 'Setas simples ajudam a indicar direção ou observações na planta. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:arrow',
      kind: 'tip',
    },
    {
      id: 'rac-tip-distance',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'distance'},
      placement: 'left',
      alignment: 'middle',
      text: 'Use distância para registrar medidas visuais de apoio no desenho. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:distance',
      kind: 'tip',
    },
    {
      id: 'rac-tip-piloti-nivel-mode',
      targetId: 'rac-piloti-nivel-mode-toggle',
      placement: 'bottom',
      alignment: 'center',
      text: 'Use este botão para alternar entre modo automático e manual. No automático, o editor pode ajustar alturas; no manual, as alturas ficam sob seu controle.',
      persistKey: 'guided-tour:rac-tip:piloti-nivel-mode',
      kind: 'tip',
    },
  ],
};
