import type {GuidedTourRegistry} from '@/components/guided-tour/ports/types.ts';

export const RAC_EDITOR_TOUR_ID = 'rac-editor-intro';

const RAC_CANVAS_OBJECT_INSERTED_EVENT = 'rac:canvas-object-inserted';
const RAC_CANVAS_OBJECT_SELECTED_EVENT = 'rac:canvas-object-selected';
const RAC_HOUSE_INITIAL_VIEWS_INSERTED_EVENT = 'rac:house-initial-views-inserted';

export const racEditorGuidedTourRegistry: GuidedTourRegistry = {
  tours: [
    {
      id: RAC_EDITOR_TOUR_ID,
      initialStepId: 'rac-hamburger',
      persistKey: 'guided-tour:rac-editor-intro:completed',
      autoStart: true,
      steps: [
        {
          id: 'rac-hamburger',
          targetId: 'rac-hamburger',
          placement: 'right',
          alignment: 'middle',
          title: 'Menu Principal',
          text: 'Use o menu principal para alternar entre as casas da Construção TETO ativa.',
          next: 'rac-user-menu',
          persistKey: 'guided-tour:rac-editor-intro:hamburger',
          kind: 'flow',
        },
        {
          id: 'rac-user-menu',
          targetId: 'rac-user-menu',
          placement: 'bottom',
          alignment: 'right',
          title: 'Perfil e Ajuda',
          text: 'Aqui ficam configurações, dicas e o acesso manual a este tutorial.',
          next: 'rac-export-pdf',
          persistKey: 'guided-tour:rac-editor-intro:user-menu',
          kind: 'flow',
        },
        {
          id: 'rac-export-pdf',
          targetId: 'rac-export-pdf',
          placement: 'bottom',
          alignment: 'right',
          title: 'Exportar PDF',
          text: 'Exporte o RAC em PDF quando precisar compartilhar a planta final.',
          next: 'rac-view-3d',
          persistKey: 'guided-tour:rac-editor-intro:export-pdf',
          kind: 'flow',
        },
        {
          id: 'rac-view-3d',
          targetId: 'rac-view-3d',
          placement: 'bottom',
          alignment: 'center',
          title: 'Visualização 3D',
          text: 'Abra a visualização 3D para conferir a casa em volume.',
          next: 'rac-zoom-menu',
          persistKey: 'guided-tour:rac-editor-intro:view-3d',
          kind: 'flow',
        },
        {
          id: 'rac-zoom-menu',
          targetId: 'rac-zoom-menu',
          placement: 'bottom',
          alignment: 'center',
          title: 'Zoom',
          text: 'O zoom também reúne seleção, navegação e ajuste da tela.',
          next: 'rac-toolbar',
          persistKey: 'guided-tour:rac-editor-intro:zoom',
          kind: 'flow',
        },
        {
          id: 'rac-toolbar',
          targetId: 'rac-toolbar',
          placement: 'right',
          alignment: 'middle',
          title: 'Barra de Ferramentas',
          text: 'A barra lateral concentra casas, elementos, linhas e ações de desenho.',
          persistKey: 'guided-tour:rac-editor-intro:toolbar',
          kind: 'flow',
        },
      ],
    },
    {
      id: 'rac-house-initial-views',
      initialStepId: 'rac-house-top-view',
      persistKey: 'guided-tour:rac-house-initial-views:completed',
      storageRevision: 'top-view',
      triggerEvent: {
        name: RAC_HOUSE_INITIAL_VIEWS_INSERTED_EVENT,
        objectKind: 'house-initial-views',
        replayWhenCompleted: true,
      },
      steps: [
        {
          id: 'rac-house-top-view',
          targetId: 'house-top-view',
          placement: 'bottom',
          alignment: 'center',
          title: 'Vista Planta',
          text: 'A vista planta mostra a casa por cima e organiza os pilotis usados como referência no desenho. Ao clicar em um dos pilotis é possível editar altura, nível e/ou contraventamento.',
          next: 'rac-house-elevation-view',
          persistKey: 'guided-tour:rac-house-initial-views:top-view',
          kind: 'flow',
        },
        {
          id: 'rac-house-elevation-view',
          targetId: 'house-elevation-view',
          placement: 'top',
          alignment: 'center',
          title: 'Vista Elevada',
          text: 'A vista elevada mostra a fachada posicionada sobre o terreno e reflete os níveis definidos nos pilotis. Ao clicar duas vezes sobre o terreno é possível editar o nível de dificuldade para cálculo de pedras.',
          persistKey: 'guided-tour:rac-house-initial-views:elevation-view',
          kind: 'flow',
        },
      ],
    },
  ],
  tips: [
    {
      id: 'rac-tip-wall',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'wall'},
      placement: 'left',
      alignment: 'middle',
      text: 'Depois de inserir um objeto ou muro, dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:wall',
      kind: 'tip',
    },
    {
      id: 'rac-tip-line',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'line'},
      placement: 'left',
      alignment: 'middle',
      text: 'Linhas podem receber texto e cor pelo editor do próprio objeto. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:line',
      kind: 'tip',
    },
    {
      id: 'rac-tip-arrow',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'arrow'},
      placement: 'left',
      alignment: 'middle',
      text: 'Setas simples ajudam a indicar direção ou observações na planta. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:arrow',
      kind: 'tip',
    },
    {
      id: 'rac-tip-distance',
      triggerEvent: {name: RAC_CANVAS_OBJECT_INSERTED_EVENT, objectKind: 'distance'},
      placement: 'left',
      alignment: 'middle',
      text: 'Use distância para registrar medidas visuais de apoio no desenho. Dê dois cliques nele para editar nome e aparência.',
      persistKey: 'guided-tour:rac-tip:distance',
      kind: 'tip',
    },
    {
      id: 'rac-tip-piloti',
      triggerEvent: {name: RAC_CANVAS_OBJECT_SELECTED_EVENT, objectKind: 'piloti-master'},
      placement: 'top',
      alignment: 'center',
      text: 'Na planta superior, selecione um piloti para abrir o editor e ajustar altura, nível e contraventamento quando necessário.',
      persistKey: 'guided-tour:rac-tip:piloti',
      kind: 'tip',
    },
    {
      id: 'rac-tip-construction-back-to-canvas',
      targetId: 'rac-construction-back-to-canvas',
      placement: 'right',
      alignment: 'middle',
      title: 'Voltar ao Canvas',
      text: 'Use este botão para retornar ao canvas da casa ativa depois de criar, arquivar, listar ou trocar construções.',
      persistKey: 'guided-tour:rac-tip:construction-back-to-canvas',
      kind: 'tip',
    },
  ],
};
